-- =============================================================================
-- PROVISYN Portable Relational Schema
-- Compatible with DuckDB, SQLite, PostgreSQL, and Snowflake
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Core Master Data
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS VENDORS (
    VENDOR_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COUNTRY_CODE VARCHAR(3) NOT NULL,
    CITY VARCHAR(100),
    PHONE VARCHAR(50),
    TIER INTEGER DEFAULT 1,
    FINANCIAL_HEALTH_SCORE DOUBLE DEFAULT 0.5,
    RELIABILITY_SCORE DOUBLE DEFAULT 0.85,
    DELIVERY_PERFORMANCE DOUBLE DEFAULT 0.90,
    CAPACITY DOUBLE DEFAULT 1000.0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MATERIALS (
    MATERIAL_ID VARCHAR(20) PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    MATERIAL_GROUP VARCHAR(10) NOT NULL,
    UNIT_OF_MEASURE VARCHAR(10) DEFAULT 'PC',
    CRITICALITY_SCORE DOUBLE DEFAULT 0.5,
    INVENTORY_DAYS INTEGER DEFAULT 30,
    UNIT_COST DOUBLE DEFAULT 50.0,
    LEAD_TIME_DAYS INTEGER DEFAULT 21,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PURCHASE_ORDERS (
    PO_ID VARCHAR(20) PRIMARY KEY,
    VENDOR_ID VARCHAR(20) NOT NULL,
    MATERIAL_ID VARCHAR(20) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DOUBLE NOT NULL,
    ORDER_DATE DATE NOT NULL,
    DELIVERY_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'OPEN',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BILL_OF_MATERIALS (
    BOM_ID VARCHAR(20) PRIMARY KEY,
    PARENT_MATERIAL_ID VARCHAR(20) NOT NULL,
    CHILD_MATERIAL_ID VARCHAR(20) NOT NULL,
    QUANTITY_PER_UNIT DOUBLE NOT NULL DEFAULT 1.0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TRADE_DATA (
    BOL_ID VARCHAR(20) PRIMARY KEY,
    SHIPPER_NAME VARCHAR(255) NOT NULL,
    SHIPPER_COUNTRY VARCHAR(3),
    CONSIGNEE_NAME VARCHAR(255) NOT NULL,
    CONSIGNEE_COUNTRY VARCHAR(3),
    HS_CODE VARCHAR(10) NOT NULL,
    HS_DESCRIPTION VARCHAR(255),
    SHIP_DATE DATE NOT NULL,
    WEIGHT_KG DOUBLE,
    VALUE_USD DOUBLE,
    PORT_OF_ORIGIN VARCHAR(100),
    PORT_OF_DESTINATION VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS REGIONS (
    REGION_CODE VARCHAR(3) PRIMARY KEY,
    REGION_NAME VARCHAR(100) NOT NULL,
    BASE_RISK_SCORE DOUBLE DEFAULT 0.0,
    GEOPOLITICAL_RISK DOUBLE DEFAULT 0.0,
    NATURAL_DISASTER_RISK DOUBLE DEFAULT 0.0,
    INFRASTRUCTURE_SCORE DOUBLE DEFAULT 0.5,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    REVENUE_PER_UNIT DOUBLE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FACTORIES (
    FACTORY_ID VARCHAR(20) PRIMARY KEY,
    REGION_CODE VARCHAR(3) NOT NULL,
    CAPACITY DOUBLE DEFAULT 500.0,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID VARCHAR(20) PRIMARY KEY,
    PRODUCT_ID VARCHAR(20) NOT NULL,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    REVENUE DOUBLE NOT NULL,
    DUE_DATE DATE NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'OPEN',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS INVENTORY (
    MATERIAL_ID VARCHAR(20) NOT NULL,
    FACTORY_ID VARCHAR(20) NOT NULL,
    ON_HAND_QTY DOUBLE NOT NULL,
    SAFETY_STOCK DOUBLE NOT NULL,
    REORDER_POINT DOUBLE NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MATERIAL_ID, FACTORY_ID)
);

CREATE TABLE IF NOT EXISTS SHIPMENTS (
    SHIPMENT_ID VARCHAR(20) PRIMARY KEY,
    PO_ID VARCHAR(20) NOT NULL,
    ORIGIN VARCHAR(100) NOT NULL,
    DESTINATION VARCHAR(100) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'IN_TRANSIT',
    ETA DATE NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- Risk & Graph Outputs
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS RISK_SCORES (
    ENTITY_TYPE VARCHAR(20) NOT NULL,
    ENTITY_ID VARCHAR(50) NOT NULL,
    RISK_SCORE DOUBLE NOT NULL,
    PAGERANK_SCORE DOUBLE,
    BETWEENNESS_SCORE DOUBLE,
    COMMUNITY_ID INTEGER,
    RISK_CATEGORY VARCHAR(50) DEFAULT 'MODERATE',
    FAILURE_PROBABILITY DOUBLE DEFAULT 0.05,
    IMPACT_SCORE DOUBLE DEFAULT 0.5,
    FINANCIAL_EXPOSURE DOUBLE DEFAULT 0.0,
    CONFIDENCE DOUBLE DEFAULT 0.85,
    TREND VARCHAR(20) DEFAULT 'STABLE',
    MODEL_VERSION VARCHAR(50),
    COMPUTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ENTITY_TYPE, ENTITY_ID)
);

CREATE TABLE IF NOT EXISTS PREDICTED_LINKS (
    SOURCE_TYPE VARCHAR(20) NOT NULL,
    SOURCE_ID VARCHAR(50) NOT NULL,
    TARGET_TYPE VARCHAR(20) NOT NULL,
    TARGET_ID VARCHAR(50) NOT NULL,
    SIMILARITY_SCORE DOUBLE NOT NULL,
    CONFIDENCE DOUBLE DEFAULT 0.75,
    EVIDENCE VARCHAR(255),
    CRITICALITY VARCHAR(20) DEFAULT 'MEDIUM',
    FINANCIAL_IMPACT DOUBLE DEFAULT 0.0,
    PREDICTION_METHOD VARCHAR(50) DEFAULT 'JACCARD',
    MODEL_VERSION VARCHAR(50),
    PREDICTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BOTTLENECKS (
    ENTITY_TYPE VARCHAR(20) NOT NULL,
    ENTITY_ID VARCHAR(50) NOT NULL,
    BETWEENNESS_SCORE DOUBLE,
    PAGERANK_SCORE DOUBLE,
    RISK_SCORE DOUBLE,
    COMMUNITY_ID INTEGER,
    BOTTLENECK_RANK INTEGER,
    ALTERNATIVE_PATH_COUNT INTEGER DEFAULT 1,
    AFFECTED_NETWORK_SIZE INTEGER DEFAULT 1,
    SEVERITY_TIER VARCHAR(20) DEFAULT 'MEDIUM',
    MODEL_VERSION VARCHAR(50),
    IDENTIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ENTITY_TYPE, ENTITY_ID)
);

CREATE TABLE IF NOT EXISTS RISK_HISTORY (
    RECORD_ID VARCHAR(50) PRIMARY KEY,
    ENTITY_TYPE VARCHAR(20) NOT NULL,
    ENTITY_ID VARCHAR(50) NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    RISK_SCORE DOUBLE NOT NULL,
    RISK_CATEGORY VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS DISRUPTIONS (
    DISRUPTION_ID VARCHAR(50) PRIMARY KEY,
    ENTITY_TYPE VARCHAR(20) NOT NULL,
    ENTITY_ID VARCHAR(50) NOT NULL,
    DISRUPTION_TYPE VARCHAR(50) NOT NULL,
    SEVERITY DOUBLE NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    DESCRIPTION VARCHAR(255)
);

-- -----------------------------------------------------------------------------
-- Decision Intelligence Entities
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS SCENARIOS (
    SCENARIO_ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SCENARIO_TYPE VARCHAR(50) NOT NULL,
    TARGET_ENTITY_TYPE VARCHAR(20),
    TARGET_ENTITY_ID VARCHAR(50),
    INTENSITY DOUBLE DEFAULT 0.5,
    DURATION_DAYS INTEGER DEFAULT 30,
    PARAMETERS_JSON TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SIMULATION_RUNS (
    RUN_ID VARCHAR(50) PRIMARY KEY,
    SCENARIO_ID VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    P10_EXPOSURE DOUBLE NOT NULL,
    P50_EXPOSURE DOUBLE NOT NULL,
    P90_EXPOSURE DOUBLE NOT NULL,
    RESILIENCE_DELTA DOUBLE NOT NULL,
    RESULTS_JSON TEXT
);

CREATE TABLE IF NOT EXISTS INTERVENTIONS (
    INTERVENTION_ID VARCHAR(50) PRIMARY KEY,
    SCENARIO_ID VARCHAR(50),
    ACTION_TYPE VARCHAR(50) NOT NULL,
    TARGET_ENTITY_ID VARCHAR(50) NOT NULL,
    COST DOUBLE NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PROPOSED',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS RECOMMENDATIONS (
    RECOMMENDATION_ID VARCHAR(50) PRIMARY KEY,
    SCENARIO_ID VARCHAR(50),
    TITLE VARCHAR(255) NOT NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    TARGET_ENTITY VARCHAR(100) NOT NULL,
    ESTIMATED_COST DOUBLE NOT NULL,
    RISK_REDUCTION DOUBLE NOT NULL,
    EXPOSURE_REDUCTION DOUBLE NOT NULL,
    RESILIENCE_IMPROVEMENT DOUBLE NOT NULL,
    RECOVERY_IMPROVEMENT DOUBLE NOT NULL,
    CONFIDENCE DOUBLE NOT NULL,
    RANK INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALERTS (
    ALERT_ID VARCHAR(50) PRIMARY KEY,
    SEVERITY VARCHAR(20) NOT NULL,
    TRIGGER_TYPE VARCHAR(50) NOT NULL,
    ENTITY_TYPE VARCHAR(20) NOT NULL,
    ENTITY_ID VARCHAR(50) NOT NULL,
    MESSAGE VARCHAR(500) NOT NULL,
    IS_PREDICTIVE BOOLEAN DEFAULT FALSE,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DECISION_HISTORY (
    DECISION_ID VARCHAR(50) PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    ACTION_TAKEN VARCHAR(255) NOT NULL,
    BEFORE_STATE_JSON TEXT,
    AFTER_STATE_JSON TEXT,
    RESILIENCE_DELTA DOUBLE,
    DECIDED_BY VARCHAR(100) DEFAULT 'Operations Lead',
    DECIDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MODEL_VERSIONS (
    MODEL_NAME VARCHAR(100) NOT NULL,
    VERSION VARCHAR(50) NOT NULL,
    TRAINING_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATASET_VERSION VARCHAR(50) NOT NULL,
    METRICS_JSON TEXT,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PRIMARY KEY (MODEL_NAME, VERSION)
);

CREATE TABLE IF NOT EXISTS FORECASTS (
    FORECAST_ID VARCHAR(50) PRIMARY KEY,
    ENTITY_TYPE VARCHAR(20) NOT NULL,
    ENTITY_ID VARCHAR(50) NOT NULL,
    FORECAST_TYPE VARCHAR(50) NOT NULL,
    HORIZON_DAYS INTEGER NOT NULL,
    PREDICTED_VALUE DOUBLE NOT NULL,
    LOWER_BOUND DOUBLE NOT NULL,
    UPPER_BOUND DOUBLE NOT NULL,
    FORECAST_DATE DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS EXTERNAL_RISK_EVENTS (
    EVENT_ID VARCHAR(50) PRIMARY KEY,
    EVENT_TYPE VARCHAR(50) NOT NULL,
    REGION_CODE VARCHAR(3),
    SEVERITY DOUBLE NOT NULL,
    SOURCE VARCHAR(100) NOT NULL,
    EVENT_DATE DATE NOT NULL,
    DETAILS TEXT
);
